name: All Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit

  integration_tests:
    runs-on: windows-latest
    needs: unit_tests
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run Integration Tests
        run: npm run test:integration

  merge:
    runs-on: ubuntu-latest
    needs: integration_tests
    if: ${{ needs.integration_tests.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set Git user
        run: |
          git config user.name chlorineCtrl
          git config user.email abirhasan5@iut-dhaka.edu
      - name: Determine default branch
        id: default_branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
      - name: Configure git to use merge by default
        run: git config pull.rebase false
      - name: Merge changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git checkout ${{ steps.default_branch.outputs.branch }}
          git pull origin ${{ steps.default_branch.outputs.branch }}
          git merge --no-ff ${{ github.sha }}
          git push origin ${{ steps.default_branch.outputs.branch }}
      - name: Show git status
        run: git status
